FeetInches to architectural string
angularsen/UnitsNet pull request #1106
Opened 2022-07-12 18:18 UTC by lwestfall

Addresses #1075. Also fixes broken image URL in readme from a long time ago :)

My coverage gutters weren't working locally so not 100% sure the new method has full coverage. Will wait for codecov to do its thing and will add test cases as needed.

2022-07-18 00:00 UTC, angularsen requested changes
Thanks! This looks great, just a few minor suggestions.

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +        /// <example>Length.FromFeetInches(3,2).ToArchitecturalString(32).ToString() outputs: "3 ft 2 in"</example>
Shouldn't the example output string be `3' - 2"` ?

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +        /// </summary>
Missing `/` before `{inchesValueIntegral}`.
Should probably also give a short description that the fractional will be omitted if it is `1`.

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +        /// <exception cref="ArgumentOutOfRangeException">Thrown when fractionDenominator is &lt; 1 (use 1 to round to nearest integer, with no fraction)</exception>
I would move the `use 1 to round to nearest integer, with no fraction` description to `fractionDenominator` parameter xmldoc, so it helps explain what values you can give.

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +                throw new ArgumentOutOfRangeException(nameof(fractionDenominator), "Denominator for fractional inch cannot be zero");
To be more precise, maybe change it to `"Denominator for fractional inch must be greater than zero."`

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +                throw new ArgumentOutOfRangeException(nameof(fractionDenominator), "Denominator for fractional inch cannot be zero");
You could also put this text in the `ArgumentOutOfRangeException` xmldoc.

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +                var gcd = greatestCommonDivisor((int)Math.Abs(numerator), fractionDenominator);
Nitpick, but `int gcd = ` would be slightly easier to read here.

2022-07-18 00:00 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Length.extra.cs
> +        /// <example>Length.FromFeetInches(3,2).ToArchitecturalString(32).ToString() outputs: "3 ft 2 in"</example>
I would love a few more examples to help illustrate how different `fractionDenominator` values determines the output for the same input.

For example:
```xmldoc
<example>
<code>
var length = Length.FromFeetInches(3, 2.6);
length.ToArchitecturalString(1)   => 3' - 3"
length.ToArchitecturalString(2)   => 3' - 2 1/2"
length.ToArchitecturalString(4)   => 3' - 2 1/2"
length.ToArchitecturalString(8)   => 3' - 2 5/8"
length.ToArchitecturalString(16)  => 3' - 2 5/8"
length.ToArchitecturalString(32)  => 3' - 2 19/32"
length.ToArchitecturalString(128) => 3' - 2 77/128"
</code>
</example>
```

2022-07-18 00:00 UTC, angularsen commented on UnitsNet.Tests/CustomCode/LengthTests.cs
> +        [InlineData(0, 2, 32, "2\"")]
Nice tests.

Can we also add these test values from my example in another PR comment? They helped me understand how it works better. 

Adapt the example to [InlineData].

```
var length = Length.FromFeetInches(3, 2.6);
length.ToArchitecturalString(1)   => 3' - 3"
length.ToArchitecturalString(2)   => 3' - 2 1/2"
length.ToArchitecturalString(4)   => 3' - 2 1/2"
length.ToArchitecturalString(8)   => 3' - 2 5/8"
length.ToArchitecturalString(16)  => 3' - 2 5/8"
length.ToArchitecturalString(32)  => 3' - 2 19/32"
length.ToArchitecturalString(128) => 3' - 2 77/128"
```

2022-07-19 12:11 UTC, lwestfall commented
Thanks for the feedback! I'll address these and try to push by the end of the week, work is a little busy for me the next couple of days.

2022-07-21 21:10 UTC, lwestfall commented
Fixes pushed! I think I addressed all comments, and I left them open so you can re-review. Let me know if you find anything else

2022-07-22 20:46 UTC, merged

2022-07-22 20:48 UTC, angularsen commented
Awesome, great work! The nuget should be out in a few minutes.

[Release UnitsNet/4.138.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.138.0)

2022-07-22 20:48 UTC, angularsen commented
Next hour, build times are very slow lately.