Added g/m2 and mg/m2 to AreaDensity with useful operators
angularsen/UnitsNet pull request #1134
Opened 2022-09-02 19:16 UTC by Brunni

Solves #1131

2022-09-02 21:01 UTC, angularsen requested changes
Thank you, this looks almost ready, just a few minor comments.

2022-09-10 10:01 UTC, Brunni commented on UnitsNet.Tests/CustomCode/AreaDensityTests.cs
> +        public void MassDividedByAreaEqualsAreaDensity()
Hi. I've add the needed unit tests. I hope it is fine.

2022-09-11 08:48 UTC, Brunni commented
The build reached maximum of 60 Minutes. Can someone restart it?

2022-09-19 17:59 UTC, Brunni commented on UnitsNet.Tests/CustomCode/AreaDensityTests.cs
> +        public void MassDividedByAreaEqualsAreaDensity()
@angularsen Hi. Can you recheck, if you find some time?

2022-10-31 21:59 UTC, angularsen commented
Sorry for the late reply, I have been missing out on email notifications for some time.

Will review soon.

2022-11-01 22:35 UTC, angularsen commented
> The build reached maximum of 60 Minutes. Can someone restart it?
> 
> EDIT: Build seems to be normally at 58 Minutes. This is quite long. How does it come?

I have no idea, sometimes the vstest process seems to hang on AppVeyor. Other times, it is just slow. It is nowhere near as slow locally, I guess the free open source VMs have very limited capacity.
In the old days it took 4-5 minutes on AppVeyor, so something has definitely changed over time.

2022-11-01 22:36 UTC, merged

2022-11-01 23:01 UTC, angularsen commented
[Release UnitsNet/4.147.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.147.0)

2022-11-01 23:03 UTC, angularsen commented
I tried upgrading a very outdated JetBrains' dotcover tool to hopefully fix the hang/slow builds. 
It seems to help locally at least. 🤞
#1146