Add new Impulse quantity with relevant units
angularsen/UnitsNet pull request #1178
Opened 2023-01-04 14:40 UTC by Sigvess92

"ImpulseUnit" was generated with enum values out of order due to the constants being ordered alphabetically. Should I manually edit the values or is this OK? I see that the two most recent quantities were merged with the same "messy" structure...

2023-01-05 21:21 UTC, angularsen requested changes
Thanks! I found a couple of things for you to look over, but other than that this looks great 👏

2023-01-05 21:21 UTC, angularsen commented on UnitsNet.Tests/CustomCode/ImpulseTests.cs
> +        protected override double PoundFootPerSecondsInOneNewtonSecond => 7.230657989877;
Verified
7.230657989877
https://www.translatorscafe.com/unit-converter/en-US/impulse/

2023-01-05 21:21 UTC, angularsen commented on UnitsNet.Tests/CustomCode/ImpulseTests.cs
> +        protected override double SlugFootPerSecondsInOneNewtonSecond => 0.224735720691;
Verified
0.224735720691
https://www.translatorscafe.com/unit-converter/en-US/impulse/

2023-01-06 07:08 UTC, Sigvess92 commented
@angularsen Thanks for the review. Updated PR.

2023-01-06 13:40 UTC, Sigvess92 commented on Common/UnitDefinitions/Impulse.json
> +          "Abbreviations": [ "pound·s" ]
Good catch. I mixed up the two units "PoundFootPerSecond" and "PoundForceSecond" here. I added the missing unit and corrected the abbreviations.

2023-01-06 22:40 UTC, merged

2023-01-06 22:59 UTC, angularsen commented
Thanks, the nuget should be out shortly.

[Release UnitsNet/5.0.0-rc010 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.0.0-rc010)

I forgot to explain, the messy enum values are intentional to reduce merge conflicts when multiple pull requests add units to the same quantity. It picks randomly from a range of available values. It then saves all allocated values to a separate file, to make sure they don't change when new units are added later, or when occasionally removing/renaming units as part of major version bumps.