added leakrate
angularsen/UnitsNet pull request #1222
Opened 2023-03-07 13:36 UTC by debendda

2023-03-07 19:22 UTC, angularsen requested changes
Hi and thank you. This looks almost good to go, a few minor comments.

2023-03-07 19:22 UTC, angularsen commented on Common/UnitDefinitions/LeakRate.json
> +    "XmlDocSummary": "The leakrate is a measure of the units of volume or mass leaking from a body.",
I don't quite understand this description. Is there an alternative way to describe it?

From another source: https://www.leybold.com/en/knowledge/vacuum-fundamentals/leak-detection/definition-and-measurement-of-vacuum-leaks

> A leak rate of QL = 1 mbar · l/s is present when in an enclosed, evacuated vessel with a volume of 1 l the pressure rises by 1 mbar per second or, where there is positive pressure in the container, pressure drops by 1 mbar.

2023-03-07 19:22 UTC, angularsen commented on Common/UnitDefinitions/LeakRate.json
> +    "BaseUnit": "PascalQubicMeterPerSecond",
`Qubic` should be `Cubic`

2023-03-07 19:22 UTC, angularsen commented on Common/UnitDefinitions/LeakRate.json
> +            "PluralName": "PascalQubicMeterPerSecond",
Meters plural

2023-03-07 19:22 UTC, angularsen commented on Common/UnitDefinitions/LeakRate.json
> +            "XmlDocRemarks": "https://de.wikipedia.org/wiki/Leckrate#Formelzeichen_und_Ma%C3%9Feinheit",
Are there English references we can link to? I didn't find an English wiki though.

2023-03-07 19:22 UTC, angularsen commented on UnitsNet.Tests/CustomCode/LeakRateTests.cs
> +        protected override double MillibarLiterPerSecondInOnePascalQubicMeterPerSecond => 10;
Verified
https://www.sensorsone.com/leak-rate-converter/

2023-03-07 19:22 UTC, angularsen commented on UnitsNet.Tests/CustomCode/LeakRateTests.cs
> +        protected override double TorrLiterPerSecondInOnePascalQubicMeterPerSecond => 7.5;
This converter says `7.50061683`?
https://www.sensorsone.com/leak-rate-converter/

2023-03-07 19:22 UTC, angularsen commented on UnitsNet.Tests/CustomCode/LeakRateTests.cs
> +        protected override double TorrLiterPerSecondInOnePascalQubicMeterPerSecond => 7.5;
This one says 7.5
https://www.helium-leak.eu/calculations-and-units/

2023-03-07 19:22 UTC, angularsen commented on UnitsNet.Tests/CustomCode/LeakRateTests.cs
> +        protected override double TorrLiterPerSecondInOnePascalQubicMeterPerSecond => 7.5;
7.5 here too
https://www.leybold.com/en-in/knowledge/vacuum-fundamentals/leak-detection/definition-and-measurement-of-vacuum-leaks

2023-03-08 07:33 UTC, debendda commented
Hi, thanks for the comments. I have improved all the suggestions. Unfortunately, I can't find an English wiki link either. I have added another link.

2023-03-08 19:16 UTC, merged

2023-03-08 19:21 UTC, angularsen commented
Looks perfect, thanks!

Nuget should be out shortly.

[Release UnitsNet/5.8.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.8.0)