Implicit cast between Duration and TimeSpan
angularsen/UnitsNet pull request #1365
Opened 2024-02-19 17:26 UTC by Muximize

See https://github.com/angularsen/UnitsNet/pull/1354#discussion_r1493344825

2024-02-19 19:38 UTC, Muximize commented
Hmm, these failing CI tests pass on my machine. Any guidance?

2024-02-23 22:24 UTC, angularsen commented
@Muximize 
Beyond multiplication, are there any cases of `TimeSpan` as left hand argument?

I can't think of any, so I'd say let's just make a breaking change and not support it. 

For multiplication, they can switch order.
Otherwise, just do an explicit cast or maybe call an extension method `.ToDuration()` on it.

2024-02-23 23:25 UTC, angularsen commented
As for the failing test case, that was my bad in a previous merged PR.
Pushed a fix to this branch.

2024-02-24 09:57 UTC, Muximize commented
I completely removed `TimeSpan` from `Duration` inference, which is a nice cleanup.

Also removed some tests for `TimeSpan` as the left operand. They all still have a counterpart that tests the reverse.

2024-02-26 06:20 UTC, angularsen requested changes
Another mistake on my part, I'll fix it.

2024-02-26 06:20 UTC, angularsen commented on UnitsNet.Tests/CustomCode/DurationTests.cs
> -
We can keep these tests, no? I would still expect an exception in these cases.

2024-02-26 06:20 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Duration.extra.cs
> -                throw new ArgumentOutOfRangeException( nameof( Duration ), "The duration is too large or small to fit in a TimeSpan" );
Oh, I guess this was here for a reason. It seems TimeSpan simply rolls over to negative if exceeding the max value. I don't like that, let's keep our checks in place and throw here.

2024-02-26 06:20 UTC, angularsen commented on UnitsNet.Tests/CustomCode/DurationTests.cs
> -
My bad, I removed some checks that seemed redundant but it appears TimeSpan simply rolls over to negative values if exceeding the max value.

I don't like that behavior, so I'd rather add these checks back.

2024-02-26 06:31 UTC, angularsen commented on UnitsNet/CustomCode/Quantities/Duration.extra.cs
> -                throw new ArgumentOutOfRangeException( nameof( Duration ), "The duration is too large or small to fit in a TimeSpan" );
Added back

2024-02-26 06:31 UTC, angularsen commented on UnitsNet.Tests/CustomCode/DurationTests.cs
> -
Added back

2024-02-26 06:33 UTC, merged