Add sol (day on Mars)
angularsen/UnitsNet pull request #1412
Opened 2024-07-12 13:26 UTC by octastylos-pseudodipteros

Closes issue #1346 by adding sol, a Mars day, which lasts 88775 seconds.

2024-08-01 07:55 UTC, octastylos-pseudodipteros commented
Hello @angularsen, sorry to bother, but I would like to ask if you could check out my pull request, thank you

2024-08-01 11:26 UTC, angularsen requested changes

2024-08-01 11:27 UTC, angularsen commented on Common/UnitDefinitions/Duration.json
> +      "FromUnitToBaseFunc": "{x} * 88775",
@octastylos-pseudodipteros Thanks for pinging, it seems my review was not submitted and not visible to you. Please take a look.

2024-08-02 20:51 UTC, octastylos-pseudodipteros commented
@angularsen thank you for your reply, the conversion value is now corrected.

2024-08-04 10:57 UTC, merged

2024-08-04 11:03 UTC, angularsen commented
Thanks, nugets are on the way.

[Release UnitsNet/5.56.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F5.56.0)

[Release UnitsNet/6.0.0-pre011 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F6.0.0-pre011)

2024-08-07 05:30 UTC, angularsen commented
The nuget was delayed due to a mistake, should be out within half an hour or so.