BaseUnit generation for the prefixed units
angularsen/UnitsNet pull request #1485
Opened 2024-12-30 21:56 UTC by lipchev

- implemented in the `QuantityJsonFilesParser` (where the `AddPrefixUnits` occurs)
- removed the skipped tests (with the "The BaseUnits are not yet supported by the prefix-generator" reason)

2024-12-30 22:03 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
>      }
This is the most iffy part- I had to hard-code the prefixes that are applicable in the base quantities.. Those aren't likely to change, but if we want to make this _properly_ we either need to do pre-parse the 'Length.json', 'Mass.json' etc in order to get their prefixes before the start of the generation (or think of other ways of storing them).

2024-12-30 22:08 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +                pair => (int)Math.Log10(double.Parse(pair.Value.Factor.TrimEnd('d'), NumberStyles.Any, CultureInfo.InvariantCulture)));
I was a little worried when casting to `(int)` but I've checked the results, there are no rounding errors..
Still, we could simply expose these as properties on the `Prefix` type.

2024-12-30 22:19 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +                pair => (int)Math.Log10(double.Parse(pair.Value.Factor.TrimEnd('d'), NumberStyles.Any, CultureInfo.InvariantCulture)));
> I was a little worried when casting to `(int)` but I've checked the results, there are no rounding errors.. Still, we could simply expose these as properties on the `Prefix` type.

Although these might have to be two properties (given that we have both binary and decimal prefixes)..

2024-12-30 22:32 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +        }
Note that when we have multiple dimensions present, there are often multiple combinations of base units that can fit a given prefix scale. This algorithm tries the smallest dimensions first, with a preference for the positive exponents.

Technically, if no exact scaling factor exists for a given quantity, having more than one dimensions- there could be another iteration after the `foreach` loop that tries to simultaneously change _two dimensions_ with a single prefix - but that would have really made my head hurt..

2025-01-01 20:02 UTC, angularsen requested changes
This seems like it works as advertised, I've checked quite a few of the generated units and they all look good to me.

The feedback is mainly about me struggling to truly understand it and that we should try to document it a bit.

2025-01-01 20:02 UTC, angularsen commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +            if (baseUnits.N is { } baseAmountUnit && dimensions.N == degree)
I took the liberty of renaming a few vars/params for my own understanding, take a look if you agree with it
99b378f9269567018357add0ce6518d534cc1b72

2025-01-01 20:43 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +        private static IEnumerable<int> GetNonZeroDegrees(this BaseDimensions dimensions)
What, you think I haven't been making shit up along the way? 😄

2025-01-01 20:57 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
>      }
Yes, I think I'll try to refactor this all into a pre-processing step for the time being, but generally speaking - I was thinking that, one day, we should maybe flattening out all of the json files:
- it's fairly easy to do: once everything is generated just re-write all json files (this should flatten out both the `Abbreviations` and the `BaseUnits`)
- this should make it easier for other parsers/generators to work with the json files
- make it slightly harder to add new quantities / units - but that shouldn't happen as often as before (especially if we could make it easy to extend on the client-side)

2025-01-01 20:58 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
>      }
Or we could do something like the `UnitRelations.json` which is overridden every time.

2025-01-01 21:26 UTC, lipchev commented on UnitsNet/GeneratedCode/Quantities/AbsorbedDoseOfIonizingRadiation.g.cs
>                      new UnitInfo<AbsorbedDoseOfIonizingRadiationUnit>(AbsorbedDoseOfIonizingRadiationUnit.Kilogray, "Kilograys", BaseUnits.Undefined, "AbsorbedDoseOfIonizingRadiation"),
Yes this a bit of an inconvenience, but if (in the future) we added the possibility to specify the _scaling factor_ then we should be able to express ***everything*** in terms of the `BaseUnits * ScalingFactor` - which would make the `FromBase/ToBase` expressions unnecessary (although for us, _regular humans_, I bet this is likely to be harder to work with)..

2025-01-01 22:32 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +        }
I haven't seen anything that suggests a particular rule, but I think the overarching objective would be to minimize the scaling factor. The current algorithm is not optimal in that regard but happens to produce near-optimal results. I don't have a concrete example, but I assume it's possible for a dimension of degree 1 to jump from `Micro` to `Giga` where the dimension with a larger exponent would have selected a _smaller jump_ such as `Micro` -> `Milli`. 

Another way to think of this is in terms of the scales of the quantities that would be produced by an operation involving the base units: _I've measured `1 g`, my flask is `1 ml`- so my density is `1 g/ml`_ (with the division producing `1 g` or `1 ml` respectively. In the absence of the ideal `g/ml` combination, then the next-best combination would be the the one that produces the smallest jump in the the `Value` of the resulting division:  `10 xx` and `0.1 xx` are clearly _better_ options then `1e9 xx` and `1e-9 xx`.
 
Figuring out the optimal solution to this problem with up to 7 dimensions and all their possible combinations isn't likely to be a trivial task (although as usual, there is probably some simple matrix multiplication that solves it in one go 😄 )

2025-01-02 19:53 UTC, lipchev commented on CodeGen/Generators/QuantityJsonFilesParser.cs
> +                }
I've included these examples in the xml-docs - it now requires a table of contents to navigate through it, but doesn't matter:  the more there is for the AI to read, the better.. 😃

2025-01-02 20:02 UTC, lipchev commented
So I refactored the code, grouping most of the functionality w.r.t. to prefixed-unit-generation as its own thing (`UnitPrefixBuilder`). 

The prefixes for the base quantities are loaded first (no more hard-coding), before generating the prefixed-units for the complete list of quantities.

Nothing changed in the generated files, so I guess that's good news.. I could experiment with a different algorithm later, but I think we already have plenty to work with..

2025-01-02 22:11 UTC, angularsen approved these changes
Valiant effort! And good news the codegen turned out the same results, it's kind of a nice sanity check in all the madness.

2025-01-02 22:11 UTC, angularsen commented on CodeGen/Helpers/PrefixBuilder/UnitPrefixBuilder.cs
> +    /// </example>
Poor soul of the next guy trying to digest this, but I can't wait for the bots to pick up my made up words for these concepts 🤣

2025-01-02 22:11 UTC, merged