updated nF core to 1.10.4-preview.11
angularsen/UnitsNet pull request #928
Opened 2021-05-20 13:35 UTC by rschiefer

2021-05-20 21:25 UTC, angularsen requested changes

2021-05-20 21:25 UTC, angularsen commented on UnitsNet.NanoFramework/GeneratedCode/Acceleration/Acceleration.nfproj
> +    <ProjectGuid>{9f2a32c7-6fcd-4987-ab43-c0b18d616762}</ProjectGuid>
I pushed a fix for deterministic project/solution guids. Please re-generate.

2021-05-21 02:05 UTC, rschiefer commented
Think I've got it all in and correct.  Apologies if not, still new to UnitsNet and nanoFramework so please bear with me.

2021-05-21 09:34 UTC, angularsen commented
Found another issue with the codegen, running codegen locally for me found `1.10.4-preview.4` as latest version instead of preview.11. Fixed in master and merged in here.

2021-05-21 09:35 UTC, merged

2021-05-21 09:39 UTC, angularsen commented
No need to apologize! This is great work. Most of the problems you ran into were due to the codegen having some minor bugs and inconsistencies that are now fixed as a result of your PR. nanoFramework is still very new to us.

Nuget is hopefully on the way out, within 30 minutes or so. 🎉
https://ci.appveyor.com/project/angularsen/unitsnet/history

[Release UnitsNet/4.92.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.92.0)

2021-05-21 11:30 UTC, rschiefer commented
Awesome, thanks SO MUCH!