json: Support custom quantities
angularsen/UnitsNet pull request #935
Opened 2021-06-08 08:41 UTC by giantmustache

The Activator is used to instantiate objects, instead of calling Quantity.From.
The assumption is that there will be a constructor of new T(double value, TUnit unit).

More info in issue #934

2021-06-08 20:28 UTC, angularsen commented
Thanks, I'll try to get around to this in a couple of days.

2021-06-12 23:04 UTC, angularsen requested changes
Great work! Just some minor things.

2021-06-12 23:04 UTC, angularsen commented on UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs
> +            var unitEnumType = _registeredTypes.Find(t => t.Unit.Name == unitEnumTypeName).Unit;
It seems like a small weakness in the current design that the namespace is not included in the serialization. But I guess for now, this is what we have to work with.

2021-07-05 06:02 UTC, giantmustache commented on UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs
> +                throw new ArgumentException($"The type {quantity} is not a {nameof(T)}");
Fixed

2021-07-05 06:04 UTC, giantmustache commented on UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs
> +            if (unitEnumType is null)
Do you mean that you would first like to search in `UnitsNet.Units.MassUnit,UnitsNet` and if you get an exception, search in the custom types?

2021-07-05 06:34 UTC, giantmustache commented on UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs
> +            _registeredTypes.Add((quantity, unit));
Done, using the unit as key in the dictionary.

2021-07-05 06:39 UTC, giantmustache commented on UnitsNet.Tests/CustomQuantities/HowMuchTests.cs
> +            var quantity = new HowMuch(12.34, HowMuchUnit.ATon);
I moved it, but `HowMuch` is situated in `UnitsNet.Tests`, so I had to add a reference `UnitsNet.Tests` to `UnitsNet.Serialization.JsonNet.Tests`

2021-07-16 09:37 UTC, angularsen commented on UnitsNet.Serialization.JsonNet/UnitsNetBaseJsonConverter.cs
> +            if (unitEnumType is null)
Looking at the code now, I don't recognize what I meant 😅

2021-07-16 09:39 UTC, merged

2021-07-16 09:46 UTC, angularsen commented
[Release JsonNet/4.4.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/JsonNet%2F4.4.0)

2021-07-16 09:47 UTC, angularsen commented
@giantmustache nuget 4.4.0 is on the way out, it would be great if you could give it a try and report back that it works.

Queued build:
https://ci.appveyor.com/project/angularsen/unitsnet/builds/40017368