Add Duration.JulianYear
angularsen/UnitsNet pull request #978
Opened 2021-10-24 20:47 UTC by ebfortin

Julian Year are used in astronomy and cosmology as a constant year length.

2021-10-30 13:34 UTC, ebfortin commented on UnitsNet.NumberExtensions/UnitsNet.NumberExtensions.csproj
> +    <TargetFrameworks>netstandard2.0</TargetFrameworks>
If we support netstandard2 then 4.7 is automatically supported as the minimum version of the .NET Framework that support netstandard2 if 4.6.1. Ref. : https://docs.microsoft.com/en-us/dotnet/standard/net-standard

I still can't build with NET4 even with NET Framework 4.8 installed. Maybe it has to do with my use of Visual Studio 2022?

2021-10-30 13:35 UTC, ebfortin commented on UnitsNet.NanoFramework/GeneratedCode/AmountOfSubstance/UnitsNet.NanoFramework.AmountOfSubstance.nuspec
> +    <version>4.101.0</version>
Yeah had some problem with that. Clicked where I shouldn't have. Thought it was resolved. Seems not.

2021-11-01 19:27 UTC, angularsen requested changes
Another thing to revert, then this should be ready to go.

2021-11-01 19:27 UTC, angularsen commented on UnitsNet.Serialization.JsonNet/UnitsNet.Serialization.JsonNet.csproj
> +    <TargetFrameworks>netstandard2.0;net40;net47</TargetFrameworks>
It seems you maybe missed this one. Changing target framework is out of scope for this PR.

Please review the final diff of the PR in the `Files Changed` tab and revert any changes that are not related to adding this unit. Whitespace changes are fine.

https://github.com/angularsen/UnitsNet/pull/978/files

2021-11-12 08:05 UTC, merged

2021-11-12 08:07 UTC, angularsen commented
[Release UnitsNet/4.103.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/UnitsNet%2F4.103.0)

2021-11-12 08:08 UTC, angularsen commented
Sorry for the delay. Nuget 4.103.0 is on the way.