Implemented the AbbreviatedUnitsConverter (JsonNet)
angularsen/UnitsNet pull request #985
Opened 2021-11-08 08:35 UTC by lipchev

.. with tests based on the SerializationTestsBase

With the default settings matches all properties and values using the StringComparer.OrdinalIgnoreCase comparer (as is the default JsonNet matching strategy). 
It is possible to customize the 'known types' information (defaults to `Quantity.ByName`) - however don't expect to have out of the box handling for `HowMuch` just yet - we're still dependent on the switch in `Quantity.From` (we should maybe consider introducing construction methods into QuantityInfo sub-classes or something).

I managed to get the decimals working with manually operating the reader (not without a few hurtles).

Finally, another break from the original serialization converters (but consistent with the DataContract / protobuf) is handling of the default types (instead of throwing an exception when no value is provided). 

PS I haven't added any handling for EmitDefaultValues = false (I assume there is one such option somewhere in JsonNet) - but I think that's hardly necessary (if we want it- we should discuss the 'default' behavior of the `Type` property)

2021-11-15 05:25 UTC, angularsen commented
I'm getting around to this one, soon.

2021-11-16 21:04 UTC, angularsen requested changes
Impressive suite of tests 👏
Some minor feedback.

2021-11-20 20:20 UTC, lipchev commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void DoubleQuantity_InScientificNotation_SerializedWithExpandedValueAndAbbreviatedUnit()
The same tests exist in [DataContractSerializerTests](https://github.com/angularsen/UnitsNet/blob/ca757677c49699a1f9a8358df8889efdc2d190c3/UnitsNet.Tests/Serialization/Xml/DataContractSerializerTests.cs#L61) and [DefaultDataContractJsonSerializerTests](https://github.com/angularsen/UnitsNet/blob/ca757677c49699a1f9a8358df8889efdc2d190c3/UnitsNet.Tests/Serialization/Json/DefaultDataContractJsonSerializerTests.cs#L65). I think I'll remove them there as well. 

I'm surprised that I couldn't find the inverse set of tests - but from memory, both DC & JsonNet also support 1E+9 as input.

2021-11-20 20:29 UTC, lipchev commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void InterfaceObject_SerializesWithoutKnownTypeInformation()
It's not very clear but here I'm talking about the [KnownType] annotation that is missing (for `Volume`) from the [TestInterfaceObject](https://github.com/angularsen/UnitsNet/blob/ca757677c49699a1f9a8358df8889efdc2d190c3/UnitsNet.Tests/Serialization/TestInterfaceObject.cs#L17). In contrast the DefaultDataContractSerializer would either [include it's own type information when the KnownType is present](https://github.com/angularsen/UnitsNet/blob/ca757677c49699a1f9a8358df8889efdc2d190c3/UnitsNet.Tests/Serialization/Json/DefaultDataContractJsonSerializerTests.cs#L200) or [throw an exception when it is not](https://github.com/angularsen/UnitsNet/blob/ca757677c49699a1f9a8358df8889efdc2d190c3/UnitsNet.Tests/Serialization/Json/DefaultDataContractJsonSerializerTests.cs#L211).

2021-11-20 21:06 UTC, lipchev commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void DoubleBaseUnitQuantity_DeserializedFromValueAndNoUnit()
As long as we have the matching public constructor- I guess we've got live with it. Although, I'm perfectly fine with this-if you're optimizing on that level, then you've probably read the fine-print, and have diligently made your own tests ensuring that the base units are such and such.

2021-11-20 21:13 UTC, lipchev commented on UnitsNet.Serialization.JsonNet/AbbreviatedUnitsConverter.cs
> +    ///     (e.g. 1, "kg", "Mass")
Excellent, what do you think of the `<inheritdoc />` should it be on top, on bottom. Is there a convention for it? VS2022 still only shows one and not the other, so I'd rather have ours..

2021-11-20 21:14 UTC, lipchev commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void DoubleIQuantity_DeserializedFromDoubleValueAndAbbreviatedUnit_CaseInsensitive()
Yes, the parameter doesn't affect the unit parsing - I'm relying on the UnitParser and it doesn't have an overload that requires the comparison to be case sensitive only. 
I've added `DoubleIQuantity_DeserializedFromDoubleValueAndAbbreviatedUnit_CaseSensitiveUnits` test for Mbar and mbar.

2021-11-20 22:12 UTC, angularsen commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void DoubleIQuantity_DeserializedFromDoubleValueAndAbbreviatedUnit_CaseInsensitive()
perfect

2021-11-20 22:18 UTC, angularsen commented on UnitsNet.Serialization.JsonNet/AbbreviatedUnitsConverter.cs
> +    ///     (e.g. 1, "kg", "Mass")
I usually put inheritdoc on top, but it doesn't seem to matter and both ways work for me.
Rider merges the two, but normally I prefer to either inherit OR specify the full xmldoc so you know what you get.

2021-11-20 22:18 UTC, angularsen commented on UnitsNet.Serialization.JsonNet.Tests/AbbreviatedUnitsConverterTests.cs
> +        public void DoubleBaseUnitQuantity_DeserializedFromValueAndNoUnit()
Agreed

2021-11-20 22:22 UTC, merged

2021-11-20 22:25 UTC, angularsen commented
[Release JsonNet/4.5.0 · angularsen/UnitsNet](https://github.com/angularsen/UnitsNet/releases/tag/JsonNet%2F4.5.0)